baseURL: "https://suchirkalra.github.io/"
title: Suchir Kalra
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research & Projects
          url: research/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Skills
          url: skills/
          weight: 3
        - name: Social Service
          url: social_service/
          weight: 4
        - name: CV
          url: Resume_Suchir_Kalra_2025.pdf
          weight: 5
        - name: Awards
          url: awards/
          weight: 6
        - name: Personal
          url:  "https://suchirkalra321.wixsite.com/portfolio/portfolio"
          weight: 7

params:
    description: "Hello! I am Suchir"
    author: Suchir Kalra
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","teaching","skills","cv","social service","personal"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Suchir Kalra
          subtitle: 'Hi, Iâ€™m Suchir, a <span style="font-weight: bold; color: #2558b3;">researcher</span>and interested in education, economic history,
          digital humanities, policy, and AI. I studied <span style="font-weight: bold; color: #2558b3;">Economics</span> and <span style="font-weight: bold; color: #2558b3;">omputer Science</span> at <span style="font-weight: bold; color: #2558b3;"><a href="https://www.ashoka.edu.in/" style="color: #2558b3; text-decoration: none;">Ashoka University</a></span>, and my  <span style="font-weight: bold; color: #2558b3;">research</span> spans diverse
          topics including <span style="font-weight: bold; color: #2558b3;">AI Art</span>, <span style="font-weight: bold; color: #2558b3;">law and tech</span>, <span style="font-weight: bold; color: #2558b3;">CAPTCHAs</span>, color: #2558b3;">the Partition of India,</span>, piezoelectricity,
          and <span style="font-weight: bold; color: #2558b3;">Indian educatio.</span>. I enjoy reading, thinking across disciplines, and performing
          theatre.'
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research & Projects
              url: research/
            - name: Teaching
              url: teaching/
            - name: Skills
              url: skills/
            - name: CV
              url: Resume_Suchir_Kalra_2025.pdf
            - name: Social Service
              url: social_service/
            - name: Awards
              url: awards/
            - name: Personal
              url:  "https://suchirkalra321.wixsite.com/portfolio/portfolio"



    socialIcons:
        - name: Email
          url: mailto:suchir.kalra@alumni.ashoka.edu.in
        - name: LinkedIn
          url: https://www.linkedin.com/in/suchir-kalra/
        - name: CV
          url: Resume_Suchir_Kalra_2025.pdf

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Suchir Kalr"
      icon: favicon.ico
      iconHeight: 17

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
