baseURL: "https://suchirk.github.io/"
title: Suchir Kalra
theme: PaperMod


enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research & Projects
          url: research/
          weight: 1
        - name: Teaching
          url: teaching/
          weight: 2
        - name: Skills
          url: skills/
          weight: 3
        - name: Social Impact
          url: social_service/
          weight: 4
        - name: CV
          url: Resume_Suchir_Kalra_2025.pdf
          weight: 5
        - name: Recognition
          url: recognition/
          weight: 6
        - name: Personal
          url:  "https://suchirkalra321.wixsite.com/portfolio/portfolio"
          weight: 7

params:
    description: "Hello! I am Suchir"
    author: Suchir Kalra
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","teaching","skills","cv","social impact", "recognition", "personal"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Suchir Kalra
          subtitle:  'Hello! I’m Suchir. A <strong><span style="color:#2558b3;">researcher</span></strong> with broad interests across
  <strong><span style="color:#2558b3;">education</span></strong>, <strong><span style="color:#2558b3;">economic history</span></strong>,
  <strong><span style="color:#2558b3;">digital humanities</span></strong>, <strong><span style="color:#2558b3;">public policy</span></strong>, <strong><span style="color:#2558b3;">artificial intelligence</span></strong> and <strong><span style="color:#2558b3;">climate change</span></strong>. I graduated from
  <strong><span style="color:#2558b3;"><a href="https://www.ashoka.edu.in/" style="color:#2558b3; text-decoration:none;">Ashoka University</a></span></strong>
  with a degree in <strong><span style="color:#2558b3;">Economics and Computer Science</span></strong>, and my
  <a href="/research/"><strong><span style="color:#2558b3;">work</span></strong></a> spans both quantitative and qualitative methods.
  I’ve conducted research on <strong><span style="color:#2558b3;">AI art</span></strong>, <strong><span style="color:#2558b3;">law and technology</span></strong>,
  <strong><span style="color:#2558b3;">CAPTCHAs</span></strong>, the <strong><span style="color:#2558b3;">Partition of India</span></strong>,
  <strong><span style="color:#2558b3;">piezoelectricity</span></strong>, and India’s <strong><span style="color:#2558b3;">education sector</span></strong>.
  These topics may seem disparate, but they’re connected by my curiosity about how <strong><span style="color:#2558b3;">technology, society, and history</span></strong> interact.
  When I’m not researching, you’ll find me <strong><span style="color:#2558b3;">reading</span></strong> or performing as a
  <strong><span style="color:#2558b3;">theatre actor</span></strong>. Always excited to talk about ideas—so feel free to reach out!'
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research & Projects
              url: research/
            - name: Teaching
              url: teaching/
            - name: Skills
              url: skills/
            - name: CV
              url: Resume_Suchir_Kalra_2025.pdf
            - name: Social Impact
              url: social_service/
            - name: Recognition
              url: recognition/
            - name: Personal
              url:  "https://suchirkalra321.wixsite.com/portfolio/portfolio"



    socialIcons:
        - name: Email
          url: mailto:suchir.kalra@alumni.ashoka.edu.in
        - name: LinkedIn
          url: https://www.linkedin.com/in/suchir-kalra/
        - name: CV
          url: Resume_Suchir_Kalra_2025.pdf

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Suchir Kalra"
      icon: favicon.ico
      iconHeight: 17

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
